version: '3'
services:
    go:
        image: golang:latest
        container_name:  go
        volumes:
            - .:/go/src/app
        networks:
            - default
        command: go run /go/src/app/surveillance.go

networks:
    default:
        external:
            name: configuration_net